server:
  port: 8761

spring:
  profiles:
    default: local
  application:
    name: discovery-service

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
